### ISSUE TITLE
Timeout Issue with bb8-redis 0.14.0 on GCP Memorystore Redis

### ISSUE THREAD

**Issue by lee-hen** [djc/bb8#188]
Hi,

I've encountered an issue after updating to bb8-redis 0.14.0. Local tests showed no problems, but on GCP with Memorystore Redis, timeouts occur every 10-20 minutes for 2-3 users.

**Comment by djc** [comment]
What is your config setup? In particular, do you customize the connection timeout?

Given the timing of your issue, I think this might be related to the recent bb8 0.8.2 update instead of the bb8-redis changes themselves (which only bumped the version of the upstream redis crate). bb8 0.8.2 included some fairly invasive changes from #186 in order to try and fix a potential deadlock issue. As part of this, the crate is now a little more strict about timing out for getting a connection (see in particular https://github.com/djc/bb8/commit/016c164156e91d95c410316f609192977637554a).

**Comment by djc** [comment]
#187 identified an issue in 0.8.2 which might somehow be related to your issue, so maybe have a look at #189.

**Comment by lee-hen** [comment]
I'll take a look at the bb8 0.8.2 update and the related issues you mentioned, particularly #187 and #189. Since I haven't customized the connection timeout and I'm experiencing timeouts on GCP with Memorystore Redis, it does seem plausible that the recent bb8 changes could be the culprit.

I'll check out your suggestions and update you on any progress.

Thanks again for your help!

**Comment by djc** [comment]
Please consider having your organization [sponsor](https://github.com/sponsors/djc) me on GitHub.

**Comment by lee-hen** [comment]
> Please consider having your organization [sponsor](https://github.com/sponsors/djc) me on GitHub.

I need to check with my company first, so please wait a moment.
